# Generated by Django 4.2.25 on 2025-11-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_categoria_cliente_contato_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_estoque',
            field=models.BooleanField(default=True),
        ),
    ]
