# Generated by Django 4.2.25 on 2025-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_produto_em_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
