# Generated by Django 4.2.25 on 2025-11-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
