# Generated by Django 4.2.25 on 2025-11-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
